---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-exporter
  labels:
    app.kubernetes.io/name: wazuh-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wazuh-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wazuh-exporter
    spec:
      containers:
      - name: wazuh-exporter
        image: kennyopennix/wazuh-exporter:latest
        env:
          - name: WAZUH_API_HOST
            value: "wazuh"
          - name: WAZUH_API_PORT
            value: "55000"
          - name: WAZUH_API_USERNAME
            value: "wazuh-wui"
          - name: WAZUH_API_PASSWORD
            value: ""
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-exporter
  labels:
    app.kubernetes.io/name: wazuh-exporter
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: wazuh-exporter
